# TODO: review deploy script works but is not right

stages:
  - test
#  - deploy

test:
  stage: test
  image: python:3.9
  before_script:
    - echo "nameserver 192.168.2.126" > /etc/resolv.conf
    - export PYTHONPATH=$PYTHONPATH:/builds/diegargon/monnet-gateway/src
    - pip install -r requirements.txt

  script:
    - pytest -v tests/test_monnet_gateway.py

deploy_to_github:
  stage: deploy
  image: alpine/git
  script:
    - echo "nameserver 192.168.2.126" > /etc/resolv.conf
    - git config --global user.name "GitLabCI"
    - git config --global user.email "ci-bot@no.domain"
    - git remote remove github || true
    - git remote add github https://oauth2:${GITHUB_TOKEN}@github.com/diegargon/monnet-gateway.git
    - git remote -v
    - git fetch github main
    - git checkout -b main || git checkout main
    - git pull --rebase --strategy=recursive --strategy-option=theirs github main || true
#    - git merge github/main --strategy=recursive --strategy-option=ours --allow-unrelated-histories
    - git add .
    - git diff .gitlab-ci.yml
    - git status
    - git commit -m "Deploy changes from GitLab CI"  || echo "Nothing to commit"
#    - git push -u github main
    - git push --force github main