# TODO: review deploy script works but is not right

stages:
  - test
  - deploy

before_script:
  - echo "nameserver 192.168.2.126" > /etc/resolv.conf
test:
  stage: test
  image: python:3.9
  variables:
    PYTHONPATH: "/builds/diegargon/monnet-core:/builds/diegargon/monnet-core/monnet_gateway"


  script:
    - pip install -r requirements.txt
    - python -c "import sys; print('PYTHONPATH is:', sys.path)"
    - ls -al
    - pytest -v tests/test_monnet_gateway.py

deploy_to_github:
  stage: deploy
  when: manual
  image: alpine/git
  script:
    # Configura el usuario de Git
    - git config --global user.name "GitLabCI"
    - git config --global user.email "ci-bot@no.domain"

      # Elimina el remote de GitHub si existe
    - git remote remove github || true
    
    # Agrega el remote de GitHub
    - git remote add github https://oauth2:${GITHUB_TOKEN}@github.com/diegargon/monnet-core.git
    - git remote -v

    # Crea la rama main si no existe (en caso de que haya sido eliminada con git init)
    - git checkout -b main  # Si la rama main no existe, la creamos
    
    # Elimina todo el historial de GitHub y reinicia el repositorio
    - rm -rf .git
    - git init
    - git remote add github https://oauth2:${GITHUB_TOKEN}@github.com/diegargon/monnet-core.git

    # Agrega todos los archivos locales
    - git add .
    
    # Realiza un commit (esto es necesario antes de hacer el push)
    - git commit -m "Re-uploading the local code"
    
    # Verifica que la rama `main` exista
    - git branch
    
    # Realiza el push a GitHub, forzando el reemplazo de lo remoto
    - git push --force github main

#    - git config --global user.name "GitLabCI"
#    - git config --global user.email "ci-bot@no.domain"
#    - git remote remove github || true
#    - git remote add github https://oauth2:${GITHUB_TOKEN}@github.com/diegargon/monnet-core.git
#    - git remote -v
#    - git fetch github main
#    - git checkout -b main || git checkout main
#    - git diff origin/main github/main
#    - git pull --rebase --strategy=recursive --strategy-option=theirs github main || true
##    - git merge github/main --strategy=recursive --strategy-option=ours --allow-unrelated-histories
#    - git add .
#    - git diff .gitlab-ci.yml
#    - git status
#    - git commit -m "Deploy changes from GitLab CI"  || echo "Nothing to commit"
##    - git push -u github main
#    - git push --force github main