# TODO: review deploy script works but is not right

stages:
  - test
  - deploy

before_script:
  - echo "nameserver 192.168.2.126" > /etc/resolv.conf
test:
  stage: test
  image: python:3.9
  variables:
    PYTHONPATH: "/builds/diegargon/monnet-core:/builds/diegargon/monnet-core/monnet_gateway"


  script:
    - pip install -r requirements.txt
    - python -c "import sys; print('PYTHONPATH is:', sys.path)"
    - ls -al
    - pytest -v tests/test_monnet_gateway.py

deploy_to_github:
  stage: deploy
  when: manual
  image: alpine/git
  script:
    # Configura el usuario de Git
    - git config --global user.name "GitLabCI"
    - git config --global user.email "ci-bot@no.domain"

    # Agrega el remote de GitHub
    - git remote remove github || true
    - git remote add github https://oauth2:${GITHUB_TOKEN}@github.com/diegargon/monnet-core.git
    - git remote -v

    # Verifica que estás en la rama correcta (main)
    - git checkout main
    - git fetch github
    - git branch -r
    - git merge --allow-unrelated-histories github/main -X ours
    - git show-ref
    #- git merge -X ours github/main
    - git gc 
    - git fsck --full
    - 
    #- git push --no-thin github main
     # Forzar el push para sobrescribir GitHub
    - git push --force github main
#    - git config --global user.name "GitLabCI"
#    - git config --global user.email "ci-bot@no.domain"
#    - git remote remove github || true
#    - git remote add github https://oauth2:${GITHUB_TOKEN}@github.com/diegargon/monnet-core.git
#    - git remote -v
#    - git fetch github main
#    - git checkout -b main || git checkout main
#    - git diff origin/main github/main
#    - git pull --rebase --strategy=recursive --strategy-option=theirs github main || true
##    - git merge github/main --strategy=recursive --strategy-option=ours --allow-unrelated-histories
#    - git add .
#    - git diff .gitlab-ci.yml
#    - git status
#    - git commit -m "Deploy changes from GitLab CI"  || echo "Nothing to commit"
##    - git push -u github main
#    - git push --force github main