- name: Shutdown a Windows system
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Shutdown the Windows system
      win_shutdown:
        reboot: no
        force: yes
        msg: "System shutdown initiated by Ansible"
