# @meta
# id: "std_cmd-uptime"
# name: "cmd-uptime"
# desc: "Obtener información de tiempo de actividad del sistema"
# os: { linux, posix }
# tags: { uptime }
---
- name: Gather uptime information
  hosts: all
  gather_facts: false
  tasks:
    - name: Get uptime
      command: uptime
      register: uptime_info

    - name: Show uptime
      debug:
        msg: "{{ uptime_info.stdout }}"
