# @meta
# id: "std_ip-info"
# name: "ip-info"
# desc: "Gather IP address and routes"
# os: { linux, posix }
# tags: { ip, network }
---
- name: Gather IP address and routes
  hosts: all
  gather_facts: false
  tasks:
    - name: Get IP addresses
      command: ip addr show
      register: ip_info

    - name: Show IP address information
      debug:
        msg: "{{ ip_info.stdout }}"
