- name: Reboot a Linux system
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Reboot the system
      reboot:
        reboot_timeout: 600  # Tiempo de espera para el reinicio en segundos (ajustable)
        test_command: uptime  # Comando para verificar si el sistema está disponible
