# @meta
# id: "std-gather-min-facts"
# name: "std-cmd-gather-min-facts"
# desc: "Gather minimal facts"
# os: { linux, posix }
# tags: { facts }
---
- name: Minimal fact gathering
  hosts: all
  gather_facts: false
  tasks:
    - name: Gather minimal facts
      ansible.builtin.setup:
        gather_subset:
          - "min"
