# @meta
# id: "std-service-facts"
# name: "std-service-facts"
# description: "Gather service facts"
# os: ["linux", "posix"]
# tags: ["services", "facts", "std"]
---
- name: Gather service facts
  hosts: all
  gather_facts: true #need for services
  tasks:
    - name: Gather facts about services
      service_facts:

    - name: Show all service facts
      debug:
        msg: |
          Running Services:
          {% for service, details in services.items() if details.state == 'running' %}
          {{ details.name }}, Source: {{ details.source }}, Status: {{ details.status | default('N/A') }}
          {% endfor %}

          Stopped Services:
          {% for service, details in services.items() if details.state == 'stopped' %}
          {{ details.name }}, Source: {{ details.source }}, Status: {{ details.status | default('N/A') }}
          {% endfor %}

          Other States:
          {% for service, details in services.items() if details.state not in ['running', 'stopped'] %}
          {{ details.name }}, Source: {{ details.source }}, State: {{ details.state }}, Status: {{ details.status | default('N/A') }}
          {% endfor %}
