# @meta
# id: "std-buildin-shell-free-linux"
# name: "std-buildin-shell-free-linux"
# description: "Get memory usage"
# os: ["linux", "posix"]
# tags: ["resources", "memory"]
# version: "0.1"
---
- name: Get memory usage
  hosts: all
  gather_facts: false
  tasks:
    - name: Run free command
      ansible.builtin.shell:
        cmd: free -m
      register: memory_info

    - name: Show memory usage
      debug:
        msg: "{{ memory_info.stdout }}"
