# @meta
# id: "std-reboot-win"
# name: "std-reboot-win"
# description: "Reboot a Windows system"
# os: ["windows"]
# tags: ["reboot", "system"]
# version: "0.1"
---
- name: Reboot a Windows system
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Reboot the Windows system
      win_reboot:
        reboot_timeout: 600  # Tiempo de espera para el reinicio en segundos (ajustable)
        test_command: systeminfo  # Comando para verificar si el sistema está disponible
