# @meta
# id: "std-load-linux"
# name: "std-load-linux"
# desc: "Get load statistics"
# os: { linux, posix }
# tags: { performance, load }
---
- name: Get load statistics
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Fetch load statistics using uptime
      command: uptime
      register: load_stats

    - name: Display load statistics
      debug:
        msg: "{{ load_stats.stdout }}"
