# @meta
# id: "std-win-facts"
# name: "std-win-facts"
# description: "Gather Windows facts"
# os: ["windows"]
# tags: ["facts"]
---
- name: Gather facts from Windows hosts
  hosts: all
  gather_facts: false
  tasks:
    - name: Gather Windows facts
      win_facts:
