# @meta
# id: "std-gather-min-facts"
# name: "std-gather-min-facts"
# description: "Gather minimal facts"
# os: ["linux", "posix"]
# tags: ["facts", "std"]
---
- name: Minimal fact gathering
  hosts: all
  gather_facts: false
  tasks:
    - name: Gather minimal facts
      ansible.builtin.setup:
        gather_subset:
          - "min"
