# @meta
# id: "std-journald-linux"
# name: "std-journald-linux"
# description: "Get the last lines from the system journal"
# os: ["linux", "posix"]
# tags: ["journald", "logs"]
# version: "0.1"
---
- name: Get the last lines from the system journal
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Get the last 10 lines of the system journal
      command: journalctl -n "{{ num_lines | default(25) }}"
      register: debug_output

    - name: Display the journal output
      debug:
        msg: "{{ debug_output.stdout_lines }}"