# @meta
# id: "std-reboot-linux"
# name: "std-reboot-linux"
# description: "Reboot a Linux system"
# os: ["linux", "posix"]
# tags: ["reboot", "system"]
# version: "0.1"
---
- name: Reboot a Linux system
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Reboot the system
      reboot:
        reboot_timeout: 600  # Tiempo de espera para el reinicio en segundos (ajustable)
        test_command: uptime  # Comando para verificar si el sistema está disponible
