# @meta
# id: "std-cmd-sstuln"
# name: "std-cmd-sstuln"
# description: "Get network socket information"
# os: ["linux", "posix"]
# tags: ["network"]
# version: "0.1"
---
- name: Get network socket information
  hosts: all
  gather_facts: false
  tasks:
    - name: Run ss command
      command: ss -tuln
      register: socket_info

    - name: Show socket info
      debug:
        msg: "{{ socket_info.stdout }}"
