# @meta
# id: "std-setup"
# name: "std-setup"
# description: "Gather system information"
# os: ["linux", "posix", "windows"]
# tags: ["system", "facts", "std"]
---
- name: Gather system information
  hosts: all
  gather_facts: false
  tasks:
    - name: Gather facts about the system
      setup:
