# @meta
# id: "std-mysql-performance"
# name: "std-mysql-performance"
# description: "Monitor MySQL performance and resource usage"
# os: ["linux", "posix"]
# vars:
#   - name: db_username
#     type: str
#     default: "root"
#     description: "Nombre de usuario de la base de datos"
#   - name: db_password
#     type: str_password
#     required: true
#     description: "Contraseña de la base de datos"
# tags: ["mysql", "performance", "monitoring"]
# requires:
#   - ansible_version: "2.9"
# dependencies:
#   - PyMySQL: ">=0.9.3"
---
- name: Monitor MySQL performance and resource usage
  hosts: all
  become: true
  gather_facts: false

  vars:
    db_username: "{{ db_username | default('root') }}"
    db_password: "{{ db_password }}"

  tasks:
    - name: Ensure MySQL is running
      service:
        name: mysql
        state: started

    # Check MySQL CPU usage (by MySQL process)
    - name: Get MySQL CPU usage
      shell: ps -eo %cpu,comm | grep mysqld
      register: mysql_cpu_usage
      changed_when: false

    - name: Display MySQL CPU usage
      debug:
        msg: "MySQL CPU Usage: {{ mysql_cpu_usage.stdout }}"

    # Check number of running queries
    - name: Get running queries
      mysql_query:
        login_user: "{{ db_username }}"
        login_password: "{{ db_password }}"
        login_host: localhost
        login_unix_socket: /run/mysqld/mysqld.sock
        query: "SHOW PROCESSLIST;"
      register: running_queries
      changed_when: false

    - name: Display number of running queries
      debug:
        msg: "Running queries: {{ running_queries.query_result | length }}"

    # Check slow queries (based on slow query log if enabled)
    - name: Check if the slow query log file exists
      stat:
        path: /var/log/mysql/mysql-slow.log
      register: slow_log_file

    - name: Get slow queries from the log
      shell: tail -n 10 /var/log/mysql/mysql-slow.log
      register: slow_queries
      changed_when: false
      when: slow_log_file.stat.exists

    - name: Display slow queries
      debug:
        msg: "Slow Queries: {{ slow_queries.stdout }}"
      when: slow_log_file.stat.exists

    - name: Handle missing slow query log
      debug:
        msg: "The slow query log file does not exist."
      when: not slow_log_file.stat.exists

    # Check MySQL status related to cache and buffer
    - name: Get MySQL InnoDB buffer pool status
      mysql_query:
        login_user: "{{ db_username }}"
        login_password: "{{ db_password }}"
        login_host: localhost
        login_unix_socket: /run/mysqld/mysqld.sock
        query: "SHOW GLOBAL STATUS LIKE 'Innodb_buffer_pool%';"
      register: innodb_status
      changed_when: false

    - name: Display InnoDB buffer pool status
      debug:
        msg: "{{ innodb_status.query_result }}"

    # Get MySQL query cache status
    - name: Get MySQL query cache status
      mysql_query:
        login_user: "{{ db_username }}"
        login_password: "{{ db_password }}"
        login_host: localhost
        login_unix_socket: /run/mysqld/mysqld.sock
        query: "SHOW GLOBAL STATUS LIKE 'Qcache%';"
      register: query_cache_status
      changed_when: false

    - name: Display query cache status
      debug:
        msg: "{{ query_cache_status.query_result }}"

    # Check MySQL connection stats
    - name: Get MySQL connections statistics
      mysql_query:
        login_user: "{{ db_username }}"
        login_password: "{{ db_password }}"
        login_host: localhost
        login_unix_socket: /run/mysqld/mysqld.sock
        query: "SHOW STATUS LIKE 'Threads_connected';"
      register: connection_status
      changed_when: false

    - name: Display MySQL connection statistics
      debug:
        msg: "Threads connected: {{ connection_status.query_result[0][0] if connection_status.query_result | length > 0 else 'No data found' }}"
