# @meta
# id: "std-cmd-uptime"
# name: "std-cmd-uptime"
# description: "Obtain system uptime information"
# os: ["linux", "posix"]
# tags: ["uptime"]
# version: "0.1"
---
- name: Gather uptime information
  hosts: all
  gather_facts: false
  tasks:
    - name: Get uptime
      command: uptime
      register: uptime_info

    - name: Show uptime
      debug:
        msg: "{{ uptime_info.stdout }}"
