- name: Get the last lines of syslog
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Get the last 10 lines of syslog
      command: tail -n "{{ num_lines | default(25) }}" /var/log/syslog
      register: debug_output

    - name: Debug syslog output
      debug:
        msg: "{{ debug_output.stdout_lines }}"